version: '3'
services:
        adguard-server:
                container_name: adguardhome
                image: adguard/adguardhome
                restart: always
                ports:
                      - "53:53/tcp"
                      - "53:53/udp"
                      - "67:67/udp"
                      - "68:68/tcp"
                      - "68:68/udp"
                      - "853:853"     
                      - "8001:80/tcp"
                      - "8002:443/tcp"
                      - "8000:3000/tcp"
                volumes:
                      - "/home/adguard/work:/opt/adguardhome/work"
                      - "/home/adguard/conf:/opt/adguardhome/conf"
